user nginx;
#user www-data;
worker_processes auto;

events {
    worker_connections 768;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;

#    include  /vagrant/nginx/conf/leadnews.conf/*.conf;
    upstream  heima-app-gateway{
       #server 192.168.33.11:51601;
       server 10.0.2.2:51601;
    }

    upstream  heima-wemedia-gateway{
       server 10.0.2.2:51602;
    }

    server {
       listen 8801;
       location / {
            root /usr/share/nginx/html/app-web;
            index index.html;
       }


        location /app/ {
                rewrite ^/app/(.*)$ /$1 break;  # 去掉 /app 前缀
                proxy_pass http://heima-app-gateway;
                proxy_set_header HOST $host;  # 不改变源请求头的值
                proxy_pass_request_body on;  #开启获取请求体
                proxy_pass_request_headers on;  #开启获取请求头
                proxy_set_header X-Real-IP $remote_addr;   # 记录真实发出请求的客户端IP
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  #记录代理信息
        }
    }

    server {
       listen 8802;
       location / {
            root /usr/share/nginx/html/wemedia-web;
            index index.html;
       }


        location /wemedia/MEDIA/ {
                rewrite ^/wemedia/MEDIA/(.*)$ /$1 break;  # 去掉 /wemedia/MEDIA 前缀
                proxy_pass http://heima-wemedia-gateway;
                proxy_set_header HOST $host;  # 不改变源请求头的值
                proxy_pass_request_body on;  #开启获取请求体
                proxy_pass_request_headers on;  #开启获取请求头
                proxy_set_header X-Real-IP $remote_addr;   # 记录真实发出请求的客户端IP
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  #记录代理信息
        }
    }
}