version: '3.5'

services:
  nacos:
    image: nacos/nacos-server:v2.2.2
    container_name: nacos
    restart: always
    ports:
      - "8848:8848"  # Nacos Web 界面访问端口
    environment:
      - MODE=standalone  # 单机模式
      - SPRING_DATASOURCE_PLATFORM=mysql  # 这告诉 Nacos 使用 MySQL 数据库
      - MYSQL_SERVICE_HOST=mysql          # 这里要确保服务名称与 mysql 容器的名称一致
      - MYSQL_SERVICE_PORT=3306           # 端口应保持 3306
      - MYSQL_SERVICE_DB_NAME=nacos_config
      - MYSQL_SERVICE_USER=nacos_user
      - MYSQL_SERVICE_PASSWORD=nacos_password
    volumes:
      - ./logs:/home/nacos/logs  # 持久化日志
    networks:
      - nacos_net
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: nacos_config
      MYSQL_USER: nacos_user
      MYSQL_PASSWORD: nacos_password
    volumes:
      - mysql_data:/var/lib/mysql                                             # 持久化存储数据
      - /vagrant/mysql/redmine/init.sql:/docker-entrypoint-initdb.d/init.sql  # 挂载初始化脚本
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci  # 设置字符集和排序规 则
    networks:
      - nacos_net
      - redmine_net

  nginx:
    image: nginx:1-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /vagrant/nginx/conf/nginx.conf:/etc/nginx/nginx.conf    # 主配置文件
      - /vagrant/nginx/html:/usr/share/nginx/html               # 网站根目录
      - /vagrant/nginx/log:/var/log/nginx                       # 日志文件目录
    networks:
      - nacos_net

  redmine:
    image: redmine:5.0.5
    container_name: redmine
    restart: always
    ports:
      - "3000:3000"
    environment:
      REDMINE_DB_DATABASE: redmine_db      # 指定要连接的数据库名称
      REDMINE_DB_MYSQL: mysql              # 指定数据库名称
      REDMINE_DB_USERNAME: redmine_user      # 指定数据库用户
      REDMINE_DB_PASSWORD: redmine_password  # 指定数据库用户密码
      REDMINE_DB_ENCODING: utf8mb4
      REDMINE_DB_PORT: 3306
      TZ: Asia/Taipei
    volumes:
      - ./redmine/files:/usr/src/redmine/files  # 持久化文件存储
      - ./redmine/plugins:/usr/src/redmine/plugins  # 持久化插件存储
      - ./redmine/themes:/usr/src/redmine/public/themes  # 持久化主题存储
      - ./redmine/config/configuration.yml:/usr/src/redmine/config/configuration.yml  # 持久化配置文件
    networks:
      - redmine_net
    depends_on:
      - mysql

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # API 端口
      - "9001:9001"  # 控制台端口
    volumes:
      - minio_data:/data # 存储数据的卷
    environment:
      MINIO_ROOT_USER: "minioadmin"       # 访问的用户名
      MINIO_ROOT_PASSWORD: "minioadmin"   # 访问的密码（生产环境应修改）
    command: server /data --console-address ":9001" # 设置控制台端口

networks:
  nacos_net:
    name: nacos_net # 自定义网络名称
    driver: bridge # 使用桥接驱动
  redmine_net:
    name: redmine_net
    driver: bridge
volumes:
  mysql_data:
  minio_data:
    driver: local